version: '3'
services:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
